CREATE TABLE IF NOT EXISTS yak_workflow_schedule (
    id VARCHAR(80) NOT NULL,
    workflow_id VARCHAR(80) NOT NULL,
    name VARCHAR(200) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'CRON',
    cron_expression VARCHAR(160) NOT NULL,
    timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Shanghai',
    start_time DATETIME(3) NULL,
    end_time DATETIME(3) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
    execution_strategy VARCHAR(32) NOT NULL DEFAULT 'SERIAL_WAIT',
    misfire_strategy VARCHAR(32) NOT NULL DEFAULT 'FIRE_ONCE',
    input_json LONGTEXT NOT NULL,
    last_fire_time DATETIME(3) NULL,
    next_fire_time DATETIME(3) NULL,
    create_time DATETIME(3) NOT NULL,
    update_time DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_yak_workflow_schedule_name (workflow_id, name),
    KEY idx_yak_workflow_schedule_status (status, update_time),
    KEY idx_yak_workflow_schedule_workflow (workflow_id, update_time),
    KEY idx_yak_workflow_schedule_next_fire (status, next_fire_time),
    CONSTRAINT fk_yak_workflow_schedule_workflow
      FOREIGN KEY (workflow_id) REFERENCES yak_workflow_definition(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
