import type { ScreenTemplate } from '../model';

const hudPanel = {
  frame: 'hud' as const,
  glow: true,
  effect: 'scan' as const,
  borderColor: 'rgba(70, 217, 255, 0.24)',
  background: 'linear-gradient(180deg, rgba(8, 31, 50, 0.78), rgba(4, 17, 31, 0.68))',
  shadow: '0 18px 50px rgba(0, 0, 0, 0.18), inset 0 0 30px rgba(70, 217, 255, 0.035)',
};

const metricPanel = {
  frame: 'hud' as const,
  glow: true,
  padding: 15,
  borderColor: 'rgba(70, 217, 255, 0.24)',
  background: 'linear-gradient(135deg, rgba(12, 39, 59, 0.92), rgba(5, 20, 36, 0.72))',
};

export const commandCenterTemplate: ScreenTemplate = {
  version: 1,
  id: 'data-intelligence-command-center',
  name: '数据智能指挥中心',
  description: '中心链路地图、左右趋势分析与底部实时状态流组成的高视觉冲击数字化大屏。',
  category: '数据中心',
  width: 1920,
  height: 1080,
  theme: {
    background: 'radial-gradient(circle at 50% 43%, rgba(25, 145, 207, 0.16) 0%, rgba(4, 17, 31, 0.02) 42%, transparent 62%), linear-gradient(180deg, #061423 0%, #030b16 52%, #020812 100%)',
    textColor: '#eaf8ff',
    mutedTextColor: '#7195aa',
    primaryColor: '#46d9ff',
    panelBackground: 'rgba(5, 22, 37, 0.82)',
    panelBorderColor: 'rgba(70, 217, 255, 0.18)',
    fontFamily: 'DIN Alternate, Inter, PingFang SC, Microsoft YaHei, sans-serif',
  },
  components: [
    {
      id: 'header-left',
      type: 'text',
      x: 38,
      y: 28,
      width: 410,
      height: 32,
      data: { content: 'YAK OPS  /  DATA OBSERVABILITY GRID' },
      style: { fontSize: 12, fontWeight: 600, letterSpacing: 2.4, color: '#6f9bb2' },
    },
    {
      id: 'screen-title',
      type: 'text',
      x: 510,
      y: 16,
      width: 900,
      height: 58,
      data: { content: '全域数据智能指挥中心' },
      style: {
        fontSize: 30,
        fontWeight: 700,
        letterSpacing: 7,
        textAlign: 'center',
        color: '#effcff',
        accentColor: '#46d9ff',
        glow: true,
      },
    },
    {
      id: 'header-right',
      type: 'text',
      x: 1470,
      y: 28,
      width: 412,
      height: 32,
      data: { content: '● LIVE  ·  SYSTEM HEALTH 99.98%' },
      style: { fontSize: 12, fontWeight: 600, letterSpacing: 1.8, textAlign: 'right', color: '#5cf2b5', glow: true, accentColor: '#5cf2b5' },
    },
    {
      id: 'throughput-trend',
      type: 'line',
      x: 36,
      y: 108,
      width: 400,
      height: 278,
      title: '全链路吞吐趋势',
      subtitle: 'INGEST / TRANSFORM / SERVE · 最近 12 小时',
      style: { ...hudPanel, accentColor: '#46d9ff' },
      data: {
        categories: ['00', '02', '04', '06', '08', '10', '12', '14', '16', '18', '20', '22'],
        series: [
          { name: '吞吐', values: [128, 142, 136, 165, 198, 224, 218, 246, 271, 258, 286, 304] },
          { name: '消费', values: [102, 116, 121, 148, 172, 196, 204, 218, 239, 236, 252, 278] },
        ],
      },
      options: { showLegend: true, showGrid: true, smooth: true, showArea: true, gradient: true, neon: true },
    },
    {
      id: 'source-health',
      type: 'bar',
      x: 36,
      y: 404,
      width: 400,
      height: 278,
      title: '数据源健康度',
      subtitle: '核心数据源实时可用率',
      style: { ...hudPanel, accentColor: '#5cf2b5' },
      data: {
        categories: ['Kafka', 'MySQL', 'PostgreSQL', 'Oracle', 'StarRocks'],
        series: [{ name: '健康度', values: [99.9, 99.4, 98.8, 97.6, 96.9] }],
      },
      options: { showLegend: false, showGrid: false, showLabels: true, horizontal: true, gradient: true, neon: true },
    },
    {
      id: 'task-type',
      type: 'pie',
      x: 36,
      y: 700,
      width: 400,
      height: 344,
      title: '任务类型分布',
      subtitle: '当前 1,284 个活跃任务',
      style: { ...hudPanel, accentColor: '#8f7cff' },
      data: {
        items: [
          { name: '离线同步', value: 418 },
          { name: 'SQL 开发', value: 336 },
          { name: '实时同步', value: 241 },
          { name: '质量检测', value: 167 },
          { name: '其他', value: 122 },
        ],
      },
      options: { showLegend: true, showLabels: false, rose: true, neon: true, gradient: true },
    },
    {
      id: 'active-nodes',
      type: 'metric',
      x: 470,
      y: 108,
      width: 214,
      height: 126,
      title: '活跃节点',
      style: { ...metricPanel, accentColor: '#46d9ff', valueColor: '#dffaff' },
      data: { value: 128, unit: '个', trend: 8.4, trendDirection: 'up', trendLabel: '较昨日' },
    },
    {
      id: 'data-volume',
      type: 'metric',
      x: 702,
      y: 108,
      width: 214,
      height: 126,
      title: '今日数据量',
      style: { ...metricPanel, accentColor: '#5cf2b5', valueColor: '#e6fff5' },
      data: { value: 18.72, unit: 'TB', trend: 12.7, trendDirection: 'up', trendLabel: '累计写入' },
    },
    {
      id: 'success-rate',
      type: 'metric',
      x: 934,
      y: 108,
      width: 214,
      height: 126,
      title: '调度成功率',
      style: { ...metricPanel, accentColor: '#8f7cff', valueColor: '#f1edff' },
      data: { value: 99.82, unit: '%', trend: 0.36, trendDirection: 'up', trendLabel: '近 24h' },
    },
    {
      id: 'active-alerts',
      type: 'metric',
      x: 1166,
      y: 108,
      width: 214,
      height: 126,
      title: '活跃告警',
      style: { ...metricPanel, accentColor: '#ffc866', valueColor: '#fff5d8' },
      data: { value: 7, unit: '条', trend: 22.2, trendDirection: 'down', trendLabel: '持续下降' },
    },
    {
      id: 'national-data-map',
      type: 'map',
      x: 470,
      y: 254,
      width: 914,
      height: 610,
      title: '全国数据链路态势',
      subtitle: '实时节点 · 跨区域传输 · 计算与质量链路',
      style: {
        frame: 'hud',
        glow: true,
        padding: 14,
        borderColor: 'rgba(70, 217, 255, 0.28)',
        background: 'radial-gradient(circle at 50% 52%, rgba(20, 108, 153, 0.16), rgba(4, 18, 31, 0.72) 58%, rgba(2, 10, 19, 0.84) 100%)',
        accentColor: '#46d9ff',
        shadow: '0 0 60px rgba(25, 160, 220, 0.08), inset 0 0 60px rgba(27, 157, 218, 0.06)',
      },
      data: {
        centerId: 'beijing',
        outline: [
          [15, 19], [22, 17], [29, 13], [37, 16], [44, 12], [51, 17], [58, 14], [65, 19],
          [72, 17], [79, 22], [83, 28], [90, 30], [87, 37], [90, 43], [86, 48], [88, 54],
          [82, 57], [78, 63], [74, 68], [69, 70], [66, 78], [60, 81], [55, 77], [49, 80],
          [44, 75], [38, 78], [34, 73], [28, 71], [25, 65], [19, 62], [18, 56], [13, 52],
          [15, 46], [10, 42], [13, 36], [9, 31], [13, 26], [11, 22],
        ],
        points: [
          { id: 'urumqi', name: '乌鲁木齐', x: 23, y: 34, tone: 'primary', value: 72 },
          { id: 'chengdu', name: '成都', x: 41, y: 58, tone: 'warning', value: 86 },
          { id: 'xian', name: '西安', x: 49, y: 47, tone: 'primary', value: 94 },
          { id: 'beijing', name: '北京 HUB', x: 66, y: 35, tone: 'primary', value: 100 },
          { id: 'harbin', name: '哈尔滨', x: 79, y: 24, tone: 'success', value: 68 },
          { id: 'wuhan', name: '武汉', x: 57, y: 56, tone: 'success', value: 91 },
          { id: 'shanghai', name: '上海', x: 75, y: 55, tone: 'primary', value: 98 },
          { id: 'guangzhou', name: '广州', x: 61, y: 73, tone: 'success', value: 96 },
          { id: 'shenzhen', name: '深圳', x: 65, y: 77, tone: 'primary', value: 99 },
          { id: 'chongqing', name: '重庆', x: 46, y: 62, tone: 'warning', value: 82 },
        ],
        routes: [
          { from: 'beijing', to: 'urumqi', intensity: 0.72 },
          { from: 'beijing', to: 'chengdu', intensity: 0.84 },
          { from: 'beijing', to: 'xian', intensity: 0.91 },
          { from: 'beijing', to: 'harbin', intensity: 0.62 },
          { from: 'beijing', to: 'wuhan', intensity: 0.94 },
          { from: 'beijing', to: 'shanghai', intensity: 1 },
          { from: 'beijing', to: 'guangzhou', intensity: 0.98 },
          { from: 'beijing', to: 'shenzhen', intensity: 1 },
          { from: 'chengdu', to: 'shanghai', intensity: 0.7 },
          { from: 'chongqing', to: 'shenzhen', intensity: 0.74 },
          { from: 'wuhan', to: 'guangzhou', intensity: 0.8 },
        ],
      },
      options: { showLabels: true, showRoutes: true, pulse: true, scan: true },
    },
    {
      id: 'quality-trend',
      type: 'line',
      x: 1484,
      y: 108,
      width: 400,
      height: 278,
      title: '数据质量趋势',
      subtitle: '完整性 / 唯一性 / 一致性综合得分',
      style: { ...hudPanel, accentColor: '#5cf2b5' },
      data: {
        categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        series: [
          { name: '质量得分', values: [94.2, 95.1, 94.8, 96.4, 97.2, 96.8, 98.1] },
          { name: 'SLA', values: [95, 95, 95, 95, 95, 95, 95] },
        ],
      },
      options: { showLegend: true, showGrid: true, smooth: true, showArea: true, gradient: true, neon: true },
    },
    {
      id: 'exception-top',
      type: 'bar',
      x: 1484,
      y: 404,
      width: 400,
      height: 278,
      title: '异常任务 TOP 5',
      subtitle: '按最近 24 小时失败次数排序',
      style: { ...hudPanel, accentColor: '#ff668f' },
      data: {
        categories: ['ods_order_sync', 'dwd_user_profile', 'ads_sales_daily', 'ods_payment', 'dws_device'],
        series: [{ name: '失败次数', values: [18, 13, 11, 8, 6] }],
      },
      options: { showLegend: false, showGrid: false, showLabels: true, horizontal: true, gradient: true, neon: true },
    },
    {
      id: 'resource-share',
      type: 'pie',
      x: 1484,
      y: 700,
      width: 400,
      height: 344,
      title: '计算资源占用',
      subtitle: '实时工作负载构成',
      style: { ...hudPanel, accentColor: '#ffc866' },
      data: {
        items: [
          { name: 'Flink', value: 38 },
          { name: 'Spark', value: 24 },
          { name: 'SeaTunnel', value: 18 },
          { name: 'SQL', value: 12 },
          { name: '其他', value: 8 },
        ],
      },
      options: { showLegend: true, showLabels: false, rose: true, neon: true },
    },
    {
      id: 'live-event-stream',
      type: 'ticker',
      x: 470,
      y: 884,
      width: 914,
      height: 160,
      title: '实时链路事件流',
      subtitle: 'LIVE DATA PIPELINE EVENTS',
      style: {
        frame: 'hud',
        glow: true,
        padding: 14,
        borderColor: 'rgba(70, 217, 255, 0.26)',
        background: 'linear-gradient(180deg, rgba(7, 29, 47, 0.88), rgba(3, 15, 28, 0.82))',
        accentColor: '#46d9ff',
      },
      data: {
        items: [
          { label: 'Kafka · order_stream', value: '126K/s', meta: '上海 → 北京', tone: 'primary' },
          { label: 'MySQL · crm_prod', value: '99.96%', meta: '同步 SLA', tone: 'success' },
          { label: 'Quality · user_profile', value: '98.7', meta: '综合质量分', tone: 'success' },
          { label: 'Flink · risk_realtime', value: '42ms', meta: 'P95 延迟', tone: 'primary' },
          { label: 'Schedule · ads_sales', value: 'RUNNING', meta: '08:42:16', tone: 'warning' },
          { label: 'Oracle · finance', value: 'RETRY', meta: '重试 1/3', tone: 'danger' },
          { label: 'StarRocks · ads', value: '1.8TB', meta: '今日写入', tone: 'primary' },
          { label: 'Dataset · customer360', value: 'V18', meta: '已发布', tone: 'success' },
        ],
      },
      options: { speed: 34 },
    },
  ],
};
