import type { ScreenTemplate } from '../model';

export const dataCenterTemplate: ScreenTemplate = {
  version: 1,
  id: 'data-center',
  name: '数据中心',
  description: '面向 DataOps 运行态展示的数据中心大屏模板。',
  category: '数据中心',
  width: 1920,
  height: 1080,
  theme: {
    background: 'linear-gradient(135deg, #06080d 0%, #0b1220 52%, #08101c 100%)',
    textColor: '#f4f7fb',
    mutedTextColor: '#7f8a9b',
    primaryColor: '#60a5fa',
    panelBackground: 'rgba(17, 24, 39, 0.9)',
    panelBorderColor: 'rgba(148, 163, 184, 0.16)',
    fontFamily: 'Inter, PingFang SC, Microsoft YaHei, sans-serif',
  },
  components: [
    {
      id: 'screen-title',
      type: 'text',
      x: 48,
      y: 28,
      width: 1000,
      height: 58,
      data: { content: 'Yak Ops · 数据中心' },
      style: { fontSize: 30, fontWeight: 600, letterSpacing: 0.5 },
    },
    {
      id: 'screen-status',
      type: 'text',
      x: 1460,
      y: 36,
      width: 412,
      height: 42,
      data: { content: '● 系统运行正常' },
      style: { fontSize: 13, textAlign: 'right', color: '#34d399' },
    },
    {
      id: 'datasources',
      type: 'metric',
      x: 48,
      y: 112,
      width: 408,
      height: 152,
      title: '数据源',
      data: { value: 42, unit: '个', trendLabel: '在线 39 · 异常 3' },
    },
    {
      id: 'tasks',
      type: 'metric',
      x: 504,
      y: 112,
      width: 408,
      height: 152,
      title: '调度任务',
      data: { value: 268, unit: '个', trend: 6.4, trendDirection: 'up', trendLabel: '近 30 天' },
    },
    {
      id: 'success-rate',
      type: 'metric',
      x: 960,
      y: 112,
      width: 408,
      height: 152,
      title: '今日成功率',
      data: { value: 98.6, unit: '%', trend: 0.7, trendDirection: 'up', trendLabel: '较昨日' },
    },
    {
      id: 'exceptions',
      type: 'metric',
      x: 1416,
      y: 112,
      width: 408,
      height: 152,
      title: '异常任务',
      data: { value: 7, unit: '个', trend: 22.2, trendDirection: 'down', trendLabel: '较昨日减少' },
    },
    {
      id: 'execution-trend',
      type: 'line',
      x: 48,
      y: 296,
      width: 1180,
      height: 360,
      title: '任务执行趋势',
      subtitle: '最近 24 小时任务运行情况',
      data: {
        categories: ['00:00', '04:00', '08:00', '12:00', '16:00', '20:00', '24:00'],
        series: [
          { name: '成功', values: [82, 61, 94, 128, 146, 132, 118] },
          { name: '异常', values: [3, 2, 5, 4, 7, 3, 2] },
        ],
      },
      options: { showLegend: true, showGrid: true, smooth: true },
    },
    {
      id: 'source-type',
      type: 'pie',
      x: 1260,
      y: 296,
      width: 612,
      height: 360,
      title: '数据源类型',
      data: {
        items: [
          { name: 'MySQL', value: 16 },
          { name: 'PostgreSQL', value: 9 },
          { name: 'Oracle', value: 7 },
          { name: 'Kafka', value: 6 },
          { name: '其他', value: 4 },
        ],
      },
      options: { showLegend: true },
    },
    {
      id: 'runtime-distribution',
      type: 'bar',
      x: 48,
      y: 688,
      width: 880,
      height: 340,
      title: '任务耗时分布',
      data: {
        categories: ['<1min', '1-5min', '5-15min', '15-30min', '>30min'],
        series: [{ name: '任务数', values: [116, 82, 41, 20, 9] }],
      },
      options: { showLegend: false, showGrid: true, showLabels: true },
    },
    {
      id: 'recent-events',
      type: 'table',
      x: 960,
      y: 688,
      width: 912,
      height: 340,
      title: '最近运行事件',
      data: {
        columns: [
          { key: 'task', title: '任务名称' },
          { key: 'type', title: '类型', width: 120 },
          { key: 'time', title: '时间', width: 160 },
          { key: 'status', title: '状态', width: 100, align: 'right' },
        ],
        rows: [
          { task: 'ods_order_sync', type: '离线同步', time: '09:18:26', status: '待处理' },
          { task: 'dwd_user_profile', type: 'SQL', time: '08:52:10', status: '重试中' },
          { task: 'ads_sales_daily', type: 'SQL', time: '08:31:45', status: '待处理' },
          { task: 'kafka_order_stream', type: '实时同步', time: '07:46:03', status: '已恢复' },
        ],
      },
    },
  ],
};
