import type { ScreenTemplate } from '../model';

export const operationCenterTemplate: ScreenTemplate = {
  version: 1,
  id: 'operation-center',
  name: '经营驾驶舱',
  description: '面向经营分析与管理汇报的深色驾驶舱模板。',
  category: '经营分析',
  width: 1920,
  height: 1080,
  theme: {
    background: 'linear-gradient(180deg, #07111f 0%, #091827 100%)',
    textColor: '#eaf3ff',
    mutedTextColor: '#7f95ad',
    primaryColor: '#38bdf8',
    panelBackground: 'rgba(13, 31, 49, 0.88)',
    panelBorderColor: 'rgba(88, 166, 210, 0.18)',
    fontFamily: 'Inter, PingFang SC, Microsoft YaHei, sans-serif',
  },
  components: [
    {
      id: 'screen-title',
      type: 'text',
      x: 48,
      y: 28,
      width: 960,
      height: 58,
      data: { content: '经营数据驾驶舱' },
      style: { fontSize: 30, fontWeight: 600, letterSpacing: 1 },
    },
    {
      id: 'screen-time',
      type: 'text',
      x: 1450,
      y: 36,
      width: 422,
      height: 42,
      data: { content: '数据更新时间  09:20' },
      style: { fontSize: 13, textAlign: 'right', color: '#7f95ad' },
    },
    {
      id: 'revenue',
      type: 'metric',
      x: 48,
      y: 112,
      width: 408,
      height: 152,
      title: '本月营收',
      data: { value: 2864.5, unit: '万元', trend: 12.6, trendDirection: 'up', trendLabel: '较上月' },
    },
    {
      id: 'orders',
      type: 'metric',
      x: 504,
      y: 112,
      width: 408,
      height: 152,
      title: '订单数量',
      data: { value: 18642, unit: '单', trend: 8.2, trendDirection: 'up', trendLabel: '较上月' },
    },
    {
      id: 'customers',
      type: 'metric',
      x: 960,
      y: 112,
      width: 408,
      height: 152,
      title: '活跃客户',
      data: { value: 5328, unit: '人', trend: 4.1, trendDirection: 'up', trendLabel: '较上月' },
    },
    {
      id: 'conversion',
      type: 'metric',
      x: 1416,
      y: 112,
      width: 408,
      height: 152,
      title: '转化率',
      data: { value: 38.7, unit: '%', trend: 1.8, trendDirection: 'up', trendLabel: '较上月' },
    },
    {
      id: 'revenue-trend',
      type: 'line',
      x: 48,
      y: 296,
      width: 1180,
      height: 360,
      title: '营收趋势',
      subtitle: '最近 7 个月经营收入变化',
      data: {
        categories: ['2月', '3月', '4月', '5月', '6月', '7月', '8月'],
        series: [
          { name: '营收', values: [1680, 1920, 2140, 2050, 2480, 2610, 2864] },
          { name: '目标', values: [1800, 1900, 2050, 2200, 2350, 2550, 2750] },
        ],
      },
      options: { showLegend: true, showGrid: true, smooth: true },
    },
    {
      id: 'channel-share',
      type: 'pie',
      x: 1260,
      y: 296,
      width: 612,
      height: 360,
      title: '渠道贡献',
      subtitle: '本月营收渠道分布',
      data: {
        items: [
          { name: '直营网点', value: 38 },
          { name: '线上渠道', value: 31 },
          { name: '合作伙伴', value: 19 },
          { name: '其他', value: 12 },
        ],
      },
      options: { showLegend: true, showLabels: false },
    },
    {
      id: 'product-ranking',
      type: 'bar',
      x: 48,
      y: 688,
      width: 880,
      height: 340,
      title: '产品销售排行',
      data: {
        categories: ['产品 A', '产品 B', '产品 C', '产品 D', '产品 E'],
        series: [{ name: '销售额', values: [860, 735, 610, 488, 352] }],
      },
      options: { showLegend: false, showGrid: true, showLabels: true },
    },
    {
      id: 'region-ranking',
      type: 'table',
      x: 960,
      y: 688,
      width: 912,
      height: 340,
      title: '区域经营排行',
      data: {
        columns: [
          { key: 'rank', title: '排名', width: 80, align: 'center' },
          { key: 'region', title: '区域' },
          { key: 'revenue', title: '营收（万）', align: 'right' },
          { key: 'growth', title: '同比', align: 'right' },
        ],
        rows: [
          { rank: 1, region: '华东', revenue: '826.4', growth: '+18.2%' },
          { rank: 2, region: '华南', revenue: '642.8', growth: '+12.9%' },
          { rank: 3, region: '华北', revenue: '511.6', growth: '+8.4%' },
          { rank: 4, region: '西南', revenue: '398.7', growth: '+6.1%' },
          { rank: 5, region: '华中', revenue: '315.0', growth: '+4.7%' },
        ],
      },
    },
  ],
};
