import type { ScreenTemplate } from '../model';

export const simpleDashboardTemplate: ScreenTemplate = {
  version: 1,
  id: 'simple-dashboard',
  name: '极简数据看板',
  description: '适合快速汇报与通用经营指标展示的浅色模板。',
  category: '通用',
  width: 1920,
  height: 1080,
  theme: {
    background: '#f4f6f8',
    textColor: '#161823',
    mutedTextColor: '#7a828e',
    primaryColor: '#2563eb',
    panelBackground: '#ffffff',
    panelBorderColor: '#e4e7ec',
    fontFamily: 'Inter, PingFang SC, Microsoft YaHei, sans-serif',
  },
  components: [
    {
      id: 'screen-title',
      type: 'text',
      x: 56,
      y: 34,
      width: 920,
      height: 56,
      data: { content: '业务数据概览' },
      style: { fontSize: 30, fontWeight: 600 },
    },
    {
      id: 'screen-subtitle',
      type: 'text',
      x: 1330,
      y: 42,
      width: 534,
      height: 40,
      data: { content: '2026 年 8 月 · 实时数据' },
      style: { fontSize: 13, textAlign: 'right', color: '#7a828e' },
    },
    {
      id: 'total-revenue',
      type: 'metric',
      x: 56,
      y: 124,
      width: 414,
      height: 160,
      title: '累计收入',
      data: { value: 8642.3, unit: '万元', trend: 9.8, trendDirection: 'up', trendLabel: '同比' },
      style: { borderRadius: 10 },
    },
    {
      id: 'new-users',
      type: 'metric',
      x: 522,
      y: 124,
      width: 414,
      height: 160,
      title: '新增用户',
      data: { value: 3268, unit: '人', trend: 5.4, trendDirection: 'up', trendLabel: '同比' },
      style: { borderRadius: 10 },
    },
    {
      id: 'orders',
      type: 'metric',
      x: 988,
      y: 124,
      width: 414,
      height: 160,
      title: '订单总量',
      data: { value: 48215, unit: '单', trend: 3.1, trendDirection: 'up', trendLabel: '同比' },
      style: { borderRadius: 10 },
    },
    {
      id: 'refund-rate',
      type: 'metric',
      x: 1450,
      y: 124,
      width: 414,
      height: 160,
      title: '退款率',
      data: { value: 1.7, unit: '%', trend: 0.4, trendDirection: 'down', trendLabel: '同比下降' },
      style: { borderRadius: 10 },
    },
    {
      id: 'business-trend',
      type: 'line',
      x: 56,
      y: 322,
      width: 1160,
      height: 380,
      title: '核心指标趋势',
      data: {
        categories: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
        series: [
          { name: '订单', values: [520, 610, 588, 720, 804, 916, 868] },
          { name: '新增用户', values: [210, 242, 235, 276, 301, 354, 332] },
        ],
      },
      options: { showLegend: true, showGrid: true, smooth: true },
      style: { borderRadius: 10 },
    },
    {
      id: 'category-sales',
      type: 'bar',
      x: 1254,
      y: 322,
      width: 610,
      height: 380,
      title: '品类销售',
      data: {
        categories: ['A 类', 'B 类', 'C 类', 'D 类', 'E 类'],
        series: [{ name: '销售额', values: [760, 628, 512, 408, 315] }],
      },
      options: { showLegend: false, showGrid: true },
      style: { borderRadius: 10 },
    },
    {
      id: 'top-products',
      type: 'table',
      x: 56,
      y: 740,
      width: 1808,
      height: 294,
      title: '重点产品表现',
      data: {
        columns: [
          { key: 'product', title: '产品' },
          { key: 'sales', title: '销售额（万）', align: 'right' },
          { key: 'orders', title: '订单数', align: 'right' },
          { key: 'conversion', title: '转化率', align: 'right' },
          { key: 'growth', title: '同比', align: 'right' },
        ],
        rows: [
          { product: '产品 A', sales: '286.4', orders: 3826, conversion: '42.6%', growth: '+18.4%' },
          { product: '产品 B', sales: '241.8', orders: 3215, conversion: '39.8%', growth: '+12.1%' },
          { product: '产品 C', sales: '198.6', orders: 2760, conversion: '36.2%', growth: '+8.7%' },
          { product: '产品 D', sales: '164.2', orders: 2198, conversion: '33.5%', growth: '+5.2%' },
        ],
      },
      style: { borderRadius: 10 },
    },
  ],
};
