package io.yak.ops.business.sync.offline.execution;

import static org.assertj.core.api.Assertions.assertThat;import static org.assertj.core.api.Assertions.assertThatThrownBy;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.atLeastOnce;import static org.mockito.Mockito.never;import static org.mockito.Mockito.verify;import static org.mockito.Mockito.verifyNoInteractions;import static org.mockito.Mockito.when;
import com.fasterxml.jackson.databind.ObjectMapper;import io.yak.ops.business.sync.offline.definition.OfflineJobDefinitionService;import io.yak.ops.business.sync.offline.domain.OfflineJobDefinition;import io.yak.ops.business.sync.offline.domain.OfflineJobExecution;import io.yak.ops.business.sync.offline.domain.core.BatchExecution;import io.yak.ops.business.sync.offline.domain.core.BatchKey;import io.yak.ops.business.sync.offline.domain.core.BatchScope;import io.yak.ops.business.sync.offline.domain.core.BatchStatus;import io.yak.ops.business.sync.offline.domain.core.BatchTrigger;import io.yak.ops.business.sync.offline.domain.core.ExecutionSnapshot;import io.yak.ops.business.sync.offline.domain.core.RetryPolicySnapshot;import io.yak.ops.business.sync.offline.engine.LinkUpClient;import io.yak.ops.business.sync.offline.engine.LinkUpClient.LinkUpTransportException;import io.yak.ops.business.sync.offline.execution.OfflineExecutionClaimService.ClaimResult;import io.yak.ops.business.sync.offline.execution.adapter.OfflineBatchScopeExecutionAdapter;import io.yak.ops.business.sync.offline.repository.OfflineBatchExecutionRepository;import io.yak.ops.business.sync.offline.repository.OfflineExecutionEventRepository;import io.yak.ops.business.sync.offline.repository.OfflineJobDefinitionRepository;import io.yak.ops.business.sync.offline.repository.OfflineJobExecutionRepository;import java.net.ConnectException;import java.util.List;import java.util.Optional;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class)
class OfflineExecutionOrchestratorTest {
  @Mock private OfflineJobDefinitionService definitionService;@Mock private OfflineExecutionClaimService claimService;@Mock private OfflineJobDefinitionRepository definitionRepository;@Mock private OfflineJobExecutionRepository executionRepository;@Mock private OfflineBatchExecutionRepository batchRepository;@Mock private OfflineBatchRuntimeService batchRuntimeService;@Mock private OfflineBatchScopeExecutionAdapter scopeExecutionAdapter;@Mock private OfflineExecutionEventRepository eventRepository;@Mock private LinkUpClient linkUpClient;private OfflineExecutionOrchestrator service;
  @BeforeEach void setUp(){service=new OfflineExecutionOrchestrator(definitionService,claimService,definitionRepository,executionRepository,batchRepository,batchRuntimeService,scopeExecutionAdapter,eventRepository,linkUpClient,new ObjectMapper());}
  @Test void shouldScheduleFailedRetryFromFrozenBatchPolicyAndDualWriteBatchTruth(){OfflineJobDefinition definition=new OfflineJobDefinition();definition.setId(10L);OfflineJobExecution execution=execution(99L,"CREATED");BatchExecution batch=frozenBatch(BatchStatus.RUNNING,BatchScope.fullSelection());when(claimService.claim(10L,"WORKFLOW",null,1)).thenReturn(new ClaimResult(definition,"{}",execution));when(batchRepository.findById(77L)).thenReturn(Optional.of(batch));when(scopeExecutionAdapter.apply(10L,"{}",batch.batchScope())).thenReturn("{}");when(definitionService.resolveExecutionJobSpec("{}")).thenReturn("{}");when(definitionRepository.findById(10L)).thenReturn(Optional.of(definition));when(linkUpClient.node()).thenThrow(new LinkUpTransportException("无法连接 Link-Up Server：http://127.0.0.1:18080",new ConnectException(),false));assertThatThrownBy(()->service.execute(10L,"WORKFLOW",null,1)).isInstanceOf(LinkUpTransportException.class);assertThat(execution.getStatus()).isEqualTo("FAILED");assertThat(execution.getNextRetryTime()).isNotNull();verify(batchRuntimeService,atLeastOnce()).persistAttempt(execution);verify(batchRepository,atLeastOnce()).findById(77L);verify(scopeExecutionAdapter).apply(10L,"{}",batch.batchScope());verify(eventRepository,atLeastOnce()).append(any());}
  @Test void retryKeepsOriginalBatchScopeAtSubmissionBoundary(){OfflineJobExecution previous=execution(98L,"FAILED");OfflineJobExecution retry=execution(99L,"CREATED");retry.setAttemptNo(2);BatchScope.CursorRange range=BatchScope.cursorRange("orders","100","200");BatchExecution batch=frozenBatch(BatchStatus.RUNNING,range);when(claimService.claimRetry(98L)).thenReturn(new ClaimResult(null,"logical",retry));when(batchRepository.findById(77L)).thenReturn(Optional.of(batch));when(scopeExecutionAdapter.apply(10L,"logical",range)).thenReturn("scoped");when(definitionService.resolveExecutionJobSpec("scoped")).thenReturn("{}");when(linkUpClient.node()).thenThrow(new LinkUpTransportException("engine down",new ConnectException(),false));assertThatThrownBy(()->service.retryFrom(previous)).isInstanceOf(LinkUpTransportException.class);verify(scopeExecutionAdapter).apply(10L,"logical",range);}
  @Test void reusedSubmittedBackfillDoesNotSubmitAgain(){OfflineJobExecution existing=execution(99L,"SUBMITTED");when(claimService.claimPendingBackfill(77L)).thenReturn(new ClaimResult(null,"logical",existing,true));assertThat(service.executePendingBackfill(77L)).isSameAs(existing);verifyNoInteractions(scopeExecutionAdapter,linkUpClient);}
  @Test void shouldMoveUncertainExecutionToUnknownAndDualWriteBatchTruth(){OfflineJobExecution execution=execution(99L,"RUNNING");execution.setStateVersion(3L);execution.setNextRetryTime(java.time.LocalDateTime.now().plusMinutes(1));execution.setEndTime(java.time.LocalDateTime.now());when(definitionRepository.findById(10L)).thenReturn(Optional.empty());service.markUnknown(execution,"状态无法确认");assertThat(execution.getStatus()).isEqualTo("UNKNOWN");assertThat(execution.getNextRetryTime()).isNull();assertThat(execution.getEndTime()).isNull();verify(batchRuntimeService).persistAttempt(execution);verify(eventRepository).append(any());}
  @Test void oldAttemptLateEventDoesNotOverwriteTaskLastProjection(){OfflineJobExecution oldAttempt=execution(99L,"RUNNING");oldAttempt.setAttemptNo(1);OfflineJobExecution latestAttempt=execution(100L,"RUNNING");latestAttempt.setAttemptNo(2);when(executionRepository.findByBatchId(77L)).thenReturn(List.of(oldAttempt,latestAttempt));service.markUnknown(oldAttempt,"旧 Attempt 晚到对账结果");verify(batchRuntimeService).persistAttempt(oldAttempt);verify(definitionRepository,never()).findById(10L);verify(definitionRepository,never()).update(any(OfflineJobDefinition.class));}
  @Test void shouldCancelWaitingRetryFromBatchTruthWithoutReadingTaskLastExecution(){BatchExecution waiting=frozenBatch(BatchStatus.WAITING_RETRY,BatchScope.fullSelection());OfflineJobExecution latest=execution(99L,"FAILED");latest.setStateVersion(4L);when(batchRuntimeService.requireLatestOccupyingBatch(10L)).thenReturn(waiting);when(batchRuntimeService.cancelWaitingRetry(waiting)).thenReturn(latest);when(definitionRepository.findById(10L)).thenReturn(Optional.empty());assertThat(service.cancelLatestBatch(10L)).isSameAs(latest);verify(batchRuntimeService).requireLatestOccupyingBatch(10L);verify(batchRuntimeService).cancelWaitingRetry(waiting);verifyNoInteractions(definitionService);verify(eventRepository).append(any());}
  @Test void batchlessLegacyExecutionIsHistoryOnlyAndCannotBeCanceled(){OfflineJobExecution history=execution(99L,"RUNNING");history.setBatchId(null);when(executionRepository.findById(99L)).thenReturn(Optional.of(history));assertThatThrownBy(()->service.cancel(99L)).isInstanceOf(IllegalStateException.class).hasMessageContaining("未绑定 Batch").hasMessageContaining("仅支持查询");verify(batchRuntimeService,never()).persistAttempt(any(OfflineJobExecution.class));verifyNoInteractions(linkUpClient);}
  @Test void batchlessLegacyExecutionCannotEnterUnknownReconcile(){OfflineJobExecution history=execution(99L,"RUNNING");history.setBatchId(null);assertThatThrownBy(()->service.markUnknown(history,"legacy timeout")).isInstanceOf(IllegalStateException.class).hasMessageContaining("未绑定 Batch").hasMessageContaining("仅支持查询");verify(batchRuntimeService,never()).persistAttempt(any(OfflineJobExecution.class));verify(definitionRepository,never()).update(any(OfflineJobDefinition.class));}
  private OfflineJobExecution execution(long id,String status){OfflineJobExecution execution=new OfflineJobExecution();execution.setId(id);execution.setJobDefinitionId(10L);execution.setBatchId(77L);execution.setStatus(status);execution.setStateVersion(1L);execution.setAttemptNo(1);return execution;}private BatchExecution frozenBatch(BatchStatus status,BatchScope scope){return new BatchExecution(77L,10L,new BatchKey("manual:test"),BatchTrigger.MANUAL,scope,new ExecutionSnapshot("{}",1,new RetryPolicySnapshot(3,30),"digest","logical"),status,List.of());}
}
