import type { DashboardDocument, PublishedDataset } from './model';

export const PUBLISHED_DATASETS: PublishedDataset[] = [
  {
    id: 'ds-sales-analysis',
    name: '销售分析数据集',
    description: '按月份、区域、渠道和产品聚合的经营分析数据，模拟由数据开发 SQL 任务发布。',
    sourceTaskId: 'sql-sales-analysis',
    sourceTaskName: 'sales_analysis.sql',
    updatedAt: '2026-08-13 21:36',
    fields: [
      { key: 'month', label: '月份', dataType: 'date', role: 'dimension', description: '业务统计月份' },
      { key: 'region', label: '区域', dataType: 'string', role: 'dimension', description: '销售区域' },
      { key: 'channel', label: '渠道', dataType: 'string', role: 'dimension', description: '订单来源渠道' },
      { key: 'product', label: '产品', dataType: 'string', role: 'dimension', description: '产品名称' },
      { key: 'salesAmount', label: '销售额', dataType: 'number', role: 'metric', description: '实际销售金额' },
      { key: 'orderCount', label: '订单数', dataType: 'number', role: 'metric', description: '完成订单数量' },
      { key: 'userCount', label: '用户数', dataType: 'number', role: 'metric', description: '成交用户数量' },
      { key: 'profit', label: '利润', dataType: 'number', role: 'metric', description: '销售毛利润' },
    ],
    rows: [
      { month: '2026-05', region: '华东', channel: '直营', product: '数据平台', salesAmount: 128, orderCount: 42, userCount: 31, profit: 34 },
      { month: '2026-05', region: '华南', channel: '渠道', product: '数据平台', salesAmount: 96, orderCount: 35, userCount: 27, profit: 21 },
      { month: '2026-05', region: '华北', channel: '直营', product: '数据治理', salesAmount: 82, orderCount: 29, userCount: 22, profit: 18 },
      { month: '2026-06', region: '华东', channel: '直营', product: '数据平台', salesAmount: 156, orderCount: 48, userCount: 36, profit: 42 },
      { month: '2026-06', region: '华南', channel: '渠道', product: '数据治理', salesAmount: 118, orderCount: 39, userCount: 30, profit: 28 },
      { month: '2026-06', region: '华北', channel: '生态', product: '数据平台', salesAmount: 91, orderCount: 31, userCount: 24, profit: 20 },
      { month: '2026-07', region: '华东', channel: '直营', product: '数据平台', salesAmount: 182, orderCount: 55, userCount: 41, profit: 51 },
      { month: '2026-07', region: '华南', channel: '渠道', product: '数据平台', salesAmount: 143, orderCount: 46, userCount: 35, profit: 36 },
      { month: '2026-07', region: '华北', channel: '生态', product: '数据治理', salesAmount: 109, orderCount: 37, userCount: 28, profit: 25 },
      { month: '2026-08', region: '华东', channel: '直营', product: '数据平台', salesAmount: 236, orderCount: 68, userCount: 49, profit: 67 },
      { month: '2026-08', region: '华南', channel: '渠道', product: '数据治理', salesAmount: 171, orderCount: 52, userCount: 39, profit: 43 },
      { month: '2026-08', region: '华北', channel: '生态', product: '数据平台', salesAmount: 137, orderCount: 44, userCount: 33, profit: 31 },
    ],
  },
  {
    id: 'ds-job-metrics',
    name: '任务运行数据集',
    description: '模拟数据开发任务运行统计，用于验证 Dashboard 对不同发布数据集的切换能力。',
    sourceTaskId: 'sql-job-metrics',
    sourceTaskName: 'ops_job_metrics.sql',
    updatedAt: '2026-08-13 21:18',
    fields: [
      { key: 'date', label: '日期', dataType: 'date', role: 'dimension' },
      { key: 'taskType', label: '任务类型', dataType: 'string', role: 'dimension' },
      { key: 'status', label: '运行状态', dataType: 'string', role: 'dimension' },
      { key: 'runCount', label: '运行次数', dataType: 'number', role: 'metric' },
      { key: 'successCount', label: '成功次数', dataType: 'number', role: 'metric' },
      { key: 'duration', label: '平均耗时', dataType: 'number', role: 'metric' },
    ],
    rows: [
      { date: '08-08', taskType: 'SQL', status: '成功', runCount: 82, successCount: 80, duration: 46 },
      { date: '08-09', taskType: 'SQL', status: '成功', runCount: 91, successCount: 88, duration: 43 },
      { date: '08-10', taskType: 'Flink', status: '成功', runCount: 74, successCount: 72, duration: 51 },
      { date: '08-11', taskType: 'SQL', status: '成功', runCount: 103, successCount: 101, duration: 40 },
      { date: '08-12', taskType: 'Flink', status: '成功', runCount: 88, successCount: 84, duration: 49 },
      { date: '08-13', taskType: 'SQL', status: '成功', runCount: 116, successCount: 113, duration: 38 },
    ],
  },
];

export const DEFAULT_DASHBOARD: DashboardDocument = {
  version: 1,
  id: 'dashboard-demo',
  name: '销售经营分析',
  activeDatasetId: 'ds-sales-analysis',
  widgets: [
    {
      id: 'metric-sales',
      type: 'metric',
      title: '销售额',
      datasetId: 'ds-sales-analysis',
      dimensions: [],
      metrics: [{ field: 'salesAmount', aggregation: 'SUM' }],
      filters: [],
      style: { showLegend: false, showDataLabels: false, smooth: false, showGrid: false },
      x: 0, y: 0, w: 6, h: 4, minW: 4, minH: 3,
    },
    {
      id: 'metric-orders',
      type: 'metric',
      title: '订单数',
      datasetId: 'ds-sales-analysis',
      dimensions: [],
      metrics: [{ field: 'orderCount', aggregation: 'SUM' }],
      filters: [],
      style: { showLegend: false, showDataLabels: false, smooth: false, showGrid: false },
      x: 6, y: 0, w: 6, h: 4, minW: 4, minH: 3,
    },
    {
      id: 'line-sales',
      type: 'line',
      title: '月度销售趋势',
      datasetId: 'ds-sales-analysis',
      dimensions: ['month'],
      metrics: [{ field: 'salesAmount', aggregation: 'SUM' }],
      filters: [],
      sort: { field: 'month', direction: 'asc' },
      style: { showLegend: false, showDataLabels: false, smooth: true, showGrid: true },
      x: 12, y: 0, w: 12, h: 8, minW: 6, minH: 6,
    },
    {
      id: 'bar-region',
      type: 'bar',
      title: '区域销售额',
      datasetId: 'ds-sales-analysis',
      dimensions: ['region'],
      metrics: [{ field: 'salesAmount', aggregation: 'SUM' }],
      filters: [],
      sort: { field: 'salesAmount', direction: 'desc' },
      style: { showLegend: false, showDataLabels: true, smooth: false, showGrid: true },
      x: 0, y: 4, w: 12, h: 8, minW: 6, minH: 6,
    },
    {
      id: 'pie-channel',
      type: 'pie',
      title: '渠道销售占比',
      datasetId: 'ds-sales-analysis',
      dimensions: ['channel'],
      metrics: [{ field: 'salesAmount', aggregation: 'SUM' }],
      filters: [],
      style: { showLegend: true, showDataLabels: false, smooth: false, showGrid: false },
      x: 12, y: 8, w: 12, h: 8, minW: 6, minH: 6,
    },
    {
      id: 'table-product',
      type: 'table',
      title: '产品经营明细',
      datasetId: 'ds-sales-analysis',
      dimensions: ['product', 'region'],
      metrics: [
        { field: 'salesAmount', aggregation: 'SUM' },
        { field: 'orderCount', aggregation: 'SUM' },
      ],
      filters: [],
      sort: { field: 'salesAmount', direction: 'desc' },
      style: { showLegend: false, showDataLabels: false, smooth: false, showGrid: false },
      x: 0, y: 16, w: 24, h: 8, minW: 10, minH: 6,
    },
  ],
};
