CREATE TABLE IF NOT EXISTS yak_audit_operation (
    id BIGINT NOT NULL AUTO_INCREMENT,
    operation_id VARCHAR(64) NOT NULL,
    operation_type VARCHAR(64) NOT NULL,
    operation_name VARCHAR(128) NOT NULL,
    actor_id VARCHAR(128) NULL,
    actor_name VARCHAR(128) NULL,
    project_id BIGINT NULL,
    project_name VARCHAR(255) NULL,
    resource_type VARCHAR(64) NULL,
    resource_id VARCHAR(128) NULL,
    resource_name VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    root_trace_id VARCHAR(128) NULL,
    error_code VARCHAR(128) NULL,
    summary VARCHAR(1024) NULL,
    metadata_json LONGTEXT NULL,
    schema_version INT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_yak_audit_operation_id (operation_id),
    KEY idx_yak_audit_operation_actor (actor_id, started_at),
    KEY idx_yak_audit_operation_project (project_id, started_at),
    KEY idx_yak_audit_operation_resource (resource_type, resource_id, started_at),
    KEY idx_yak_audit_operation_status (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS yak_audit_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    operation_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    event_category VARCHAR(32) NOT NULL,
    event_status VARCHAR(32) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    actor_id VARCHAR(128) NULL,
    resource_type VARCHAR(64) NULL,
    resource_id VARCHAR(128) NULL,
    trace_id VARCHAR(128) NULL,
    span_id VARCHAR(128) NULL,
    parent_event_id BIGINT NULL,
    reason_code VARCHAR(128) NULL,
    event_key VARCHAR(160) NULL,
    message VARCHAR(1024) NULL,
    payload_json LONGTEXT NULL,
    schema_version INT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_yak_audit_event_key (operation_id, event_key),
    KEY idx_yak_audit_event_operation (operation_id, occurred_at, id),
    KEY idx_yak_audit_event_trace (trace_id),
    KEY idx_yak_audit_event_resource (resource_type, resource_id, occurred_at),
    CONSTRAINT fk_yak_audit_event_operation
      FOREIGN KEY (operation_id) REFERENCES yak_audit_operation (operation_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
