CREATE TABLE IF NOT EXISTS yak_dev_task_execution (
    id BIGINT NOT NULL AUTO_INCREMENT,
    node_id BIGINT NOT NULL,
    task_name VARCHAR(200) NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    runtime_execution_id VARCHAR(128) NULL,
    status VARCHAR(32) NOT NULL,
    operator_name VARCHAR(128) NULL,
    duration_ms BIGINT NULL,
    error_message VARCHAR(1000) NULL,
    content LONGTEXT NOT NULL,
    config_json LONGTEXT NOT NULL,
    output_json LONGTEXT NULL,
    start_time DATETIME(6) NOT NULL,
    end_time DATETIME(6) NULL,
    create_time DATETIME(6) NOT NULL,
    update_time DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_yak_dev_task_execution_runtime (runtime_execution_id),
    KEY idx_yak_dev_task_execution_node_time (node_id, start_time),
    KEY idx_yak_dev_task_execution_status_time (status, start_time),
    KEY idx_yak_dev_task_execution_type_time (task_type, start_time),
    KEY idx_yak_dev_task_execution_operator_time (operator_name, start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
