export interface SqlBuiltinFunctionDefinition {
  name: string;
  signature: string;
  argumentsSnippet: string;
  description: string;
}

export const SQL_KEYWORDS = [
  'ADD',
  'ALL',
  'ALTER',
  'AND',
  'ANY',
  'AS',
  'ASC',
  'BETWEEN',
  'BY',
  'CASE',
  'CHECK',
  'COLUMN',
  'CONSTRAINT',
  'CREATE',
  'CROSS',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'DATABASE',
  'DEFAULT',
  'DELETE',
  'DESC',
  'DISTINCT',
  'DROP',
  'ELSE',
  'END',
  'EXCEPT',
  'EXISTS',
  'FALSE',
  'FETCH',
  'FIRST',
  'FOLLOWING',
  'FOREIGN',
  'FROM',
  'FULL',
  'GROUP',
  'HAVING',
  'IN',
  'INDEX',
  'INNER',
  'INSERT',
  'INTERSECT',
  'INTO',
  'IS',
  'JOIN',
  'KEY',
  'LAST',
  'LEFT',
  'LIKE',
  'LIMIT',
  'NATURAL',
  'NOT',
  'NULL',
  'NULLS',
  'OFFSET',
  'ON',
  'OR',
  'ORDER',
  'OUTER',
  'OVER',
  'PARTITION',
  'PRECEDING',
  'PRIMARY',
  'PROCEDURE',
  'REFERENCES',
  'RIGHT',
  'ROW',
  'ROWS',
  'SCHEMA',
  'SELECT',
  'SET',
  'TABLE',
  'THEN',
  'TRUE',
  'UNBOUNDED',
  'UNION',
  'UNIQUE',
  'UPDATE',
  'USING',
  'VALUES',
  'VIEW',
  'WHEN',
  'WHERE',
  'WITH',
] as const;

export const SQL_BUILTIN_FUNCTIONS: SqlBuiltinFunctionDefinition[] = [
  {
    name: 'COUNT',
    signature: 'COUNT(expression)',
    argumentsSnippet: '${1:*}',
    description: '返回匹配行数。',
  },
  {
    name: 'SUM',
    signature: 'SUM(expression)',
    argumentsSnippet: '${1:expression}',
    description: '返回数值表达式的合计值。',
  },
  {
    name: 'AVG',
    signature: 'AVG(expression)',
    argumentsSnippet: '${1:expression}',
    description: '返回数值表达式的平均值。',
  },
  {
    name: 'MIN',
    signature: 'MIN(expression)',
    argumentsSnippet: '${1:expression}',
    description: '返回表达式的最小值。',
  },
  {
    name: 'MAX',
    signature: 'MAX(expression)',
    argumentsSnippet: '${1:expression}',
    description: '返回表达式的最大值。',
  },
  {
    name: 'COALESCE',
    signature: 'COALESCE(value, fallback, ...)',
    argumentsSnippet: '${1:value}, ${2:fallback}',
    description: '返回参数列表中第一个非 NULL 值。',
  },
  {
    name: 'NULLIF',
    signature: 'NULLIF(value1, value2)',
    argumentsSnippet: '${1:value1}, ${2:value2}',
    description: '两个表达式相等时返回 NULL，否则返回第一个表达式。',
  },
  {
    name: 'CAST',
    signature: 'CAST(expression AS type)',
    argumentsSnippet: '${1:expression} AS ${2:type}',
    description: '将表达式转换为指定数据类型。',
  },
  {
    name: 'LOWER',
    signature: 'LOWER(string)',
    argumentsSnippet: '${1:string}',
    description: '将字符串转换为小写。',
  },
  {
    name: 'UPPER',
    signature: 'UPPER(string)',
    argumentsSnippet: '${1:string}',
    description: '将字符串转换为大写。',
  },
  {
    name: 'TRIM',
    signature: 'TRIM(string)',
    argumentsSnippet: '${1:string}',
    description: '移除字符串首尾空白字符。',
  },
  {
    name: 'SUBSTRING',
    signature: 'SUBSTRING(string FROM start FOR length)',
    argumentsSnippet: '${1:string} FROM ${2:start} FOR ${3:length}',
    description: '截取字符串的一部分。不同数据库也可能支持逗号参数语法。',
  },
  {
    name: 'CHAR_LENGTH',
    signature: 'CHAR_LENGTH(string)',
    argumentsSnippet: '${1:string}',
    description: '返回字符串字符长度。',
  },
  {
    name: 'LENGTH',
    signature: 'LENGTH(string)',
    argumentsSnippet: '${1:string}',
    description: '返回字符串长度；具体语义可能随数据库方言略有差异。',
  },
  {
    name: 'CONCAT',
    signature: 'CONCAT(value1, value2, ...)',
    argumentsSnippet: '${1:value1}, ${2:value2}',
    description: '连接多个字符串值。',
  },
  {
    name: 'REPLACE',
    signature: 'REPLACE(string, search, replacement)',
    argumentsSnippet: '${1:string}, ${2:search}, ${3:replacement}',
    description: '替换字符串中的匹配内容。',
  },
  {
    name: 'ABS',
    signature: 'ABS(number)',
    argumentsSnippet: '${1:number}',
    description: '返回数值的绝对值。',
  },
  {
    name: 'ROUND',
    signature: 'ROUND(number, digits)',
    argumentsSnippet: '${1:number}, ${2:digits}',
    description: '按指定精度对数值进行四舍五入。',
  },
  {
    name: 'CEIL',
    signature: 'CEIL(number)',
    argumentsSnippet: '${1:number}',
    description: '返回大于或等于指定数值的最小整数。',
  },
  {
    name: 'CEILING',
    signature: 'CEILING(number)',
    argumentsSnippet: '${1:number}',
    description: '返回大于或等于指定数值的最小整数。',
  },
  {
    name: 'FLOOR',
    signature: 'FLOOR(number)',
    argumentsSnippet: '${1:number}',
    description: '返回小于或等于指定数值的最大整数。',
  },
  {
    name: 'POWER',
    signature: 'POWER(base, exponent)',
    argumentsSnippet: '${1:base}, ${2:exponent}',
    description: '返回指定底数的幂。',
  },
  {
    name: 'SQRT',
    signature: 'SQRT(number)',
    argumentsSnippet: '${1:number}',
    description: '返回数值的平方根。',
  },
  {
    name: 'MOD',
    signature: 'MOD(dividend, divisor)',
    argumentsSnippet: '${1:dividend}, ${2:divisor}',
    description: '返回除法运算的余数。',
  },
  {
    name: 'EXTRACT',
    signature: 'EXTRACT(part FROM expression)',
    argumentsSnippet: '${1:part} FROM ${2:expression}',
    description: '从日期或时间表达式中提取指定部分。',
  },
  {
    name: 'ROW_NUMBER',
    signature: 'ROW_NUMBER()',
    argumentsSnippet: '',
    description: '在窗口中为每一行分配连续序号。',
  },
  {
    name: 'RANK',
    signature: 'RANK()',
    argumentsSnippet: '',
    description: '在窗口中计算带并列的排名。',
  },
  {
    name: 'DENSE_RANK',
    signature: 'DENSE_RANK()',
    argumentsSnippet: '',
    description: '在窗口中计算无排名间隙的并列排名。',
  },
  {
    name: 'LAG',
    signature: 'LAG(value, offset)',
    argumentsSnippet: '${1:value}, ${2:offset}',
    description: '返回窗口中当前行之前指定偏移位置的值。',
  },
  {
    name: 'LEAD',
    signature: 'LEAD(value, offset)',
    argumentsSnippet: '${1:value}, ${2:offset}',
    description: '返回窗口中当前行之后指定偏移位置的值。',
  },
];
