export const WORKFLOW_NODE_WIDTH = 240;
export const WORKFLOW_NODE_HORIZONTAL_GAP = 60;
export const WORKFLOW_NODE_VERTICAL_GAP = 39;

export const WORKFLOW_HANDLE_SIZE = 16;
export const WORKFLOW_HANDLE_TOP = 16;
export const WORKFLOW_HANDLE_OFFSET = -9;
export const WORKFLOW_EDGE_HANDLE_OVERLAP = WORKFLOW_HANDLE_SIZE / 2;
