package io.yak.ops.business.sync.realtime.service;
import com.fasterxml.jackson.databind.*;import io.yak.ops.business.sync.realtime.domain.CdcPipelineSpec;import io.yak.ops.business.sync.realtime.engine.*;import io.yak.ops.business.sync.realtime.engine.HttpRealtimeEngineGateway.GatewayException;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import javax.sql.DataSource;import org.springframework.beans.factory.annotation.Qualifier;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class RealtimeJobService {
 private final JdbcTemplate db;private final ObjectMapper json;private final PipelineYamlCompiler compiler;private final RealtimeEngineGateway gateway;
 public RealtimeJobService(@Qualifier("yakBusinessDataSource")DataSource ds,@Qualifier("realtimeObjectMapper")ObjectMapper j,PipelineYamlCompiler c,RealtimeEngineGateway g){db=new JdbcTemplate(ds);json=j;compiler=c;gateway=g;}
 @Transactional public long save(Long id,String name,String description,CdcPipelineSpec spec){String value=write(spec);String digest=sha(value);if(id==null){db.update("insert into yak_realtime_job_definition(job_name,description,spec_json,config_digest) values(?,?,?,?)",name,description,value,digest);return db.queryForObject("select id from yak_realtime_job_definition where job_name=?",Long.class,name);}db.update("update yak_realtime_job_definition set job_name=?,description=?,spec_json=?,config_digest=?,definition_version=definition_version+1,release_state='DRAFT' where id=?",name,description,value,digest,id);return id;}
 public Map<String,Object> get(long id){var rows=db.queryForList("select * from yak_realtime_job_definition where id=?",id);if(rows.isEmpty())throw new IllegalArgumentException("实时同步任务不存在");return sanitize(rows.get(0));}
 public List<Map<String,Object>> page(int page,int size){return db.queryForList("select id,job_name,description,release_state,desired_state,observed_state,definition_version,config_digest,last_error,create_time,update_time from yak_realtime_job_definition order by update_time desc limit ? offset ?",Math.min(Math.max(size,1),100),Math.max(page-1,0)*Math.min(Math.max(size,1),100));}
 @Transactional public void publish(long id){require(id);db.update("update yak_realtime_job_definition set release_state='PUBLISHED' where id=?",id);event(id,null,"PUBLISHED",null,"PUBLISHED","任务已发布");}
 public RealtimeEngineGateway.GatewayResult validate(long id){var d=require(id);return gateway.validate(compiler.compile((String)d.get("job_name"),read((String)d.get("spec_json"))));}
 @Transactional public Map<String,Object> start(long id,String requestedKey){var d=require(id);if(!"PUBLISHED".equals(d.get("release_state")))throw new IllegalStateException("请先发布任务");Integer active=db.queryForObject("select count(*) from yak_realtime_job_definition where id<>? and desired_state='RUNNING'",Integer.class,id);if(active!=null&&active>0)throw new IllegalStateException("当前 Runtime 仅允许一个活动任务，请先停止正在运行的任务");String key=requestedKey==null||requestedKey.isBlank()?UUID.randomUUID().toString():requestedKey;var old=db.queryForList("select * from yak_realtime_job_deployment where idempotency_key=?",key);if(!old.isEmpty())return sanitize(old.get(0));CdcPipelineSpec spec=read((String)d.get("spec_json"));String yaml=compiler.compile((String)d.get("job_name"),spec),digest=sha(yaml);db.update("insert into yak_realtime_job_deployment(definition_id,definition_version,spec_snapshot_json,pipeline_yaml,config_digest,idempotency_key,status) values(?,?,?,?,?,?,'SUBMITTING')",id,d.get("definition_version"),write(spec),yaml,digest,key);long dep=db.queryForObject("select id from yak_realtime_job_deployment where idempotency_key=?",Long.class,key);db.update("update yak_realtime_job_definition set desired_state='RUNNING',observed_state='STARTING' where id=?",id);try{var r=gateway.deploy(yaml,key);if(r.status()==422)fail(id,dep,"Runtime 校验失败");if(r.status()==409)fail(id,dep,"Runtime 已有活动任务");String job=r.body().path("jobId").asText(null);String runtime=r.body().path("runtimeVersion").asText(null);db.update("update yak_realtime_job_deployment set gateway_job_id=?,runtime_version=?,status=? where id=?",job,runtime,r.status()==202?"ACCEPTED":"RUNNING",dep);event(id,dep,"START_REQUESTED","STOPPED","STARTING","启动请求已提交");}catch(GatewayException e){db.update("update yak_realtime_job_deployment set status='UNKNOWN',result_uncertain=?,error_message=? where id=?",e.uncertain,e.getMessage(),dep);if(!e.uncertain)db.update("update yak_realtime_job_definition set desired_state='STOPPED',observed_state='FAILED',last_error=? where id=?",e.getMessage(),id);event(id,dep,e.uncertain?"START_UNCERTAIN":"START_FAILED","STARTING",e.uncertain?"UNKNOWN":"FAILED",e.getMessage());}return sanitize(db.queryForMap("select * from yak_realtime_job_deployment where id=?",dep));}
 @Transactional public void stop(long id){var d=require(id);var deps=db.queryForList("select * from yak_realtime_job_deployment where definition_id=? order by id desc limit 1",id);db.update("update yak_realtime_job_definition set desired_state='STOPPED',observed_state='STOPPING' where id=?",id);if(!deps.isEmpty()){String job=(String)deps.get(0).get("gateway_job_id");if(job!=null)gateway.stop(job);}event(id,deps.isEmpty()?null:((Number)deps.get(0).get("id")).longValue(),"STOP_REQUESTED",String.valueOf(d.get("observed_state")),"STOPPING","停止请求已提交");}
 public Map<String,Object> restart(long id){stop(id);return start(id,null);}
 @Transactional public void delete(long id){var d=require(id);if(!"STOPPED".equals(d.get("desired_state")))throw new IllegalStateException("运行中的任务不能删除");db.update("delete from yak_realtime_job_definition where id=?",id);}
 public List<Map<String,Object>> events(long id){return db.queryForList("select * from yak_realtime_job_event where definition_id=? order by id desc limit 200",id);}
 public JsonNode capabilities(){return gateway.capabilities();}public JsonNode logs(int tail){return gateway.logs(tail);}
 @Scheduled(fixedDelayString="${yak.sync.realtime.reconcile-delay:10000}") public void reconcile(){try{JsonNode s=gateway.status();String job=s.path("jobId").asText(null),state=s.path("state").asText("STOPPED");var active=db.queryForList("select d.id,d.gateway_job_id from yak_realtime_job_definition j join yak_realtime_job_deployment d on d.definition_id=j.id where j.desired_state='RUNNING' order by d.id desc limit 1");if(active.isEmpty())return;var a=active.get(0);long dep=((Number)a.get("id")).longValue();String expected=(String)a.get("gateway_job_id");long def=db.queryForObject("select definition_id from yak_realtime_job_deployment where id=?",Long.class,dep);if(expected!=null&&job!=null&&!expected.equals(job)){db.update("update yak_realtime_job_definition set observed_state='CONFLICT',last_error='Runtime task ID mismatch' where id=?",def);return;}db.update("update yak_realtime_job_definition set observed_state=?,last_error=null where id=?",state,def);db.update("update yak_realtime_job_deployment set status=?,gateway_job_id=coalesce(gateway_job_id,?) where id=?",state,job,dep);}catch(Exception ignored){}}
 private Map<String,Object> require(long id){return db.queryForList("select * from yak_realtime_job_definition where id=?",id).stream().findFirst().orElseThrow(()->new IllegalArgumentException("实时同步任务不存在"));}
 private void fail(long id,long dep,String m){db.update("update yak_realtime_job_deployment set status='REJECTED',error_message=? where id=?",m,dep);db.update("update yak_realtime_job_definition set desired_state='STOPPED',observed_state='FAILED',last_error=? where id=?",m,id);throw new IllegalStateException(m);}
 private void event(long id,Long dep,String type,String from,String to,String msg){db.update("insert into yak_realtime_job_event(definition_id,deployment_id,event_type,from_state,to_state,message) values(?,?,?,?,?,?)",id,dep,type,from,to,msg);}
 private CdcPipelineSpec read(String s){try{return json.readValue(s,CdcPipelineSpec.class);}catch(Exception e){throw new IllegalArgumentException("无效 Spec",e);}}private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException(e);}}private String sha(String s){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private Map<String,Object> sanitize(Map<String,Object> m){var out=new LinkedHashMap<>(m);out.remove("pipeline_yaml");return out;}
}
